[package]
edition = "2021"
name = "visual_du"
version = "0.1.0"

[dependencies]
bevy = {version = "0.7.0", features = ["dynamic"]}
bevy_prototype_lyon = "0.5.0"
walkdir = "2.3.2"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "fs_test"
path = "src/fs_test.rs"
